#ifndef __LIBSECP256K1_CONFIG__
#define __LIBSECP256K1_CONFIG__

#define HAVE_BUILTIN_EXPECT
#define USE_NUM_NONE
#define USE_FIELD_10X26
#define USE_FIELD_INV_BUILTIN
#define USE_SCALAR_8X32
#define USE_SCALAR_INV_BUILTIN

#endif // __LIBSECP256K1_CONFIG__
